package com.vincentko.vocabulary.object;

import java.util.Calendar;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vocabulary generated by hbm2java
 */
@Entity
@Table(name = "vocabulary")
public class Vocabulary  {

	private int vocabId;
	private String term;
	private String pronoun;
	private String definition;
	private Calendar pubDate;
	
	private VocabularyCategory vocabularyCategory;

	public Vocabulary() {
	}

	public Vocabulary(int vocabId) {
		this.vocabId = vocabId;
	}


	public Vocabulary(int vocabId, String term, String pronoun,
			String definition, Calendar pubDate,
			VocabularyCategory vocabularyCategory) {
		super();
		this.vocabId = vocabId;
		this.term = term;
		this.pronoun = pronoun;
		this.definition = definition;
		this.pubDate = pubDate;
		this.vocabularyCategory = vocabularyCategory;
	}

	@Id
	@Column(name="vocab_id")
	@GeneratedValue
	public int getVocabId() {
		return this.vocabId;
	}

	public void setVocabId(int vocabId) {
		this.vocabId = vocabId;
	}

	@Column(name = "term")
	public String getTerm() {
		return this.term;
	}

	public void setTerm(String term) {
		this.term = term;
	}

	@Column(name = "pronoun")
	public String getPronoun() {
		return this.pronoun;
	}

	public void setPronoun(String pronoun) {
		this.pronoun = pronoun;
	}

	@Column(name = "definition")
	public String getDefinition() {
		return this.definition;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pubDate", length = 23)
	public Calendar getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Calendar pubDate) {
		this.pubDate = pubDate;
	}

    @ManyToOne
    @JoinColumn(name="category_id")
	public VocabularyCategory getVocabularyCategory() {
		return vocabularyCategory;
	}

	public void setVocabularyCategory(VocabularyCategory vocabularyCategory) {
		this.vocabularyCategory = vocabularyCategory;
	}

}
