package com.vincentko.vocabulary.object;

import java.util.List;
import java.util.SortedSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * VocabularyCategory generated by hbm2java
 */
@Entity
@Table(name = "vocabulary_category")
public class VocabularyCategory  {

	private int categoryId;
	private String categoryName;
	
    
    private List<Vocabulary> vocabulary;

	public VocabularyCategory() {
	}

	public VocabularyCategory(int categoryId) {
		this.categoryId = categoryId;
	}


	public VocabularyCategory(int categoryId, String categoryName,
			List<Vocabulary> vocabulary) {
		super();
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.vocabulary = vocabulary;
	}

	@Id
	@Column(name="category_id")
	@GeneratedValue
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(cascade = {CascadeType.ALL})
	public List<Vocabulary> getVocabulary() {
		return vocabulary;
	}

	public void setVocabulary(List<Vocabulary> vocabulary) {
		this.vocabulary = vocabulary;
	}

}
