// default package
// Generated Oct 6, 2013 2:11:37 PM by Hibernate Tools 3.4.0.CR1

import java.sql.String;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InventoryCategory generated by hbm2java
 */
@Entity
@Table(name = "inventory_category", schema = "dbo", catalog = "feedAggregate")
public class InventoryCategory implements java.io.Serializable {

	private int categoryId;
	private String categoryName;
	private String categoryDescription;
	private Set<InventoryCategoryLink> inventoryCategoryLinks = new HashSet<InventoryCategoryLink>(
			0);

	public InventoryCategory() {
	}

	public InventoryCategory(int categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public InventoryCategory(int categoryId, String categoryName,
			String categoryDescription,
			Set<InventoryCategoryLink> inventoryCategoryLinks) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryDescription = categoryDescription;
		this.inventoryCategoryLinks = inventoryCategoryLinks;
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = 0)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", nullable = 0)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "category_description")
	public String getCategoryDescription() {
		return this.categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventoryCategory")
	public Set<InventoryCategoryLink> getInventoryCategoryLinks() {
		return this.inventoryCategoryLinks;
	}

	public void setInventoryCategoryLinks(
			Set<InventoryCategoryLink> inventoryCategoryLinks) {
		this.inventoryCategoryLinks = inventoryCategoryLinks;
	}

}
