// default package
// Generated Oct 6, 2013 2:11:37 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.String;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name = "inventory", schema = "dbo", catalog = "feedAggregate")
public class Inventory implements java.io.Serializable {

	private int itemId;
	private String itemName;
	private String itemDescription;
	private String itemCategory;
	private String itemLocation;
	private BigDecimal itemUnitprice;
	private BigDecimal itemCost;
	private int itemQuantity;
	private Date importDate;
	private Set<InventoryCategoryLink> inventoryCategoryLinks = new HashSet<InventoryCategoryLink>(
			0);

	public Inventory() {
	}

	public Inventory(int itemId, String itemName, String itemCategory,
			BigDecimal itemUnitprice, BigDecimal itemCost, int itemQuantity,
			Date importDate) {
		this.itemId = itemId;
		this.itemName = itemName;
		this.itemCategory = itemCategory;
		this.itemUnitprice = itemUnitprice;
		this.itemCost = itemCost;
		this.itemQuantity = itemQuantity;
		this.importDate = importDate;
	}

	public Inventory(int itemId, String itemName, String itemDescription,
			String itemCategory, String itemLocation, BigDecimal itemUnitprice,
			BigDecimal itemCost, int itemQuantity, Date importDate,
			Set<InventoryCategoryLink> inventoryCategoryLinks) {
		this.itemId = itemId;
		this.itemName = itemName;
		this.itemDescription = itemDescription;
		this.itemCategory = itemCategory;
		this.itemLocation = itemLocation;
		this.itemUnitprice = itemUnitprice;
		this.itemCost = itemCost;
		this.itemQuantity = itemQuantity;
		this.importDate = importDate;
		this.inventoryCategoryLinks = inventoryCategoryLinks;
	}

	@Id
	@Column(name = "item_id", unique = true, nullable = 0)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_name", nullable = 0)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_description")
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "item_category", nullable = 0)
	public String getItemCategory() {
		return this.itemCategory;
	}

	public void setItemCategory(String itemCategory) {
		this.itemCategory = itemCategory;
	}

	@Column(name = "item_location")
	public String getItemLocation() {
		return this.itemLocation;
	}

	public void setItemLocation(String itemLocation) {
		this.itemLocation = itemLocation;
	}

	@Column(name = "item_unitprice", nullable = 0, precision = 18)
	public BigDecimal getItemUnitprice() {
		return this.itemUnitprice;
	}

	public void setItemUnitprice(BigDecimal itemUnitprice) {
		this.itemUnitprice = itemUnitprice;
	}

	@Column(name = "item_cost", nullable = 0, precision = 18)
	public BigDecimal getItemCost() {
		return this.itemCost;
	}

	public void setItemCost(BigDecimal itemCost) {
		this.itemCost = itemCost;
	}

	@Column(name = "item_quantity", nullable = 0)
	public int getItemQuantity() {
		return this.itemQuantity;
	}

	public void setItemQuantity(int itemQuantity) {
		this.itemQuantity = itemQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_date", nullable = 0, length = 23)
	public Date getImportDate() {
		return this.importDate;
	}

	public void setImportDate(Date importDate) {
		this.importDate = importDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventory")
	public Set<InventoryCategoryLink> getInventoryCategoryLinks() {
		return this.inventoryCategoryLinks;
	}

	public void setInventoryCategoryLinks(
			Set<InventoryCategoryLink> inventoryCategoryLinks) {
		this.inventoryCategoryLinks = inventoryCategoryLinks;
	}

}
