package com.vincentko.inventory.object;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InventoryCategoryLink generated by hbm2java
 */
@Entity
@Table(name = "inventory_category_link")
public class InventoryCategoryLink implements java.io.Serializable {

	private int linkId;
	private Inventory inventory;
	private InventoryCategory inventoryCategory;

	public InventoryCategoryLink() {
	}

	public InventoryCategoryLink(int linkId) {
		this.linkId = linkId;
	}

	public InventoryCategoryLink(int linkId, Inventory inventory,
			InventoryCategory inventoryCategory) {
		this.linkId = linkId;
		this.inventory = inventory;
		this.inventoryCategory = inventoryCategory;
	}

	@Id
	@Column(name = "link_id")
	@GeneratedValue
	public int getLinkId() {
		return this.linkId;
	}

	public void setLinkId(int linkId) {
		this.linkId = linkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public InventoryCategory getInventoryCategory() {
		return this.inventoryCategory;
	}

	public void setInventoryCategory(InventoryCategory inventoryCategory) {
		this.inventoryCategory = inventoryCategory;
	}

}
